#!/usr/bin/env bash

# To import all bash-utils, place this at the top of your bash script:
#   source <(curl -fsS --location "https://raw.githubusercontent.com/coreyMerritt/bash-utils/refs/heads/main/src/main")

source <(curl -fsS --location "https://raw.githubusercontent.com/coreyMerritt/bash-utils/refs/heads/main/src/import")

for key in "${!functions[@]}"; do
  import "$key"
done
