#!/usr/bin/env bash

# To import all bash-utils, place this at the top of your bash script:
#   source <(curl -fsS --location "https://raw.githubusercontent.com/coreyMerritt/bash-utils/refs/heads/main/src/main")

utils=(
  "cd.project-root"
  "deploy.venv"
  "docker-deploy.postgres"
  "get.yaml-var"
  "run.cloud-script"
)

for util in "${utils[@]}"; do
  source <(curl -fsS --location "https://raw.githubusercontent.com/coreyMerritt/bash-utils/refs/heads/main/src/$util")
done
