#!/usr/bin/env bash

set -x
source <(curl -fsS --location "https://raw.githubusercontent.com/coreyMerritt/bash-utils/refs/heads/main/src/main")
echo $(getYamlVar "../../baseline-python/config/test/database.yml" "engine")
